# global settings
title: "Blair Johnson"
description: "The academic website of Blair Johnson, artificial intelligence researcher and student."
author: "Blair Johnson"
url: "blairjohnson.dev"

logo: /assets/img/headshot_banff.jpg


theme: jekyll-theme-minimal
